INCLUDE(ExternalProject)

SET(Box2D_args
        -DBOX2D_BUILD_EXAMPLES=OFF -DBOX2D_BUILD_SHARED=OFF -DBOX2D_BUILD_STATIC=ON -DBOX2D_INSTALL=OFF -DBOX2D_INSTALL_DOC=OFF
)



EXTERNALPROJECT_ADD(box2d
  SOURCE_DIR ${CRAP_LIBRARIES_PATH}/Box2D
  PREFIX ${CMAKE_BINARY_DIR}/Box2D/Build
  CMAKE_ARGS ${Box2D_args}
  BINARY_DIR ${CRAP_LIBRARIES_PATH}/Box2D/Build
  INSTALL_COMMAND ""
)
