INCLUDE(ExternalProject)

SET(Box2D_args
        -DBOX2D_BUILD_EXAMPLES=OFF -DBOX2D_BUILD_SHARED=OFF -DBOX2D_BUILD_STATIC=ON -DBOX2D_INSTALL=OFF -DBOX2D_INSTALL_DOC=OFF -D_ITERATOR_DEBUG_LEVEL=0
)

if(WIN32)

#	SET(Box2D_args ${Box2D_args} -DCMAKE_CXX_FLAGS_DEBUG="${CMAKE_CXX_FLAGS_RELEASE}" -DCMAKE_CXX_FLAGS_DEBUG="${CMAKE_CXX_FLAGS_DEBUG}" -D_ITERATOR_DEBUG_LEVEL=0
#	SET(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} /NODEFAULTLIB:LIBCMTD /NODEFAULTLIB:LIBCMT" )
#	ADD_DEFINITIONS(-DBGFX_CONFIG_RENDERER_OPENGL=1)
endif(WIN32)


EXTERNALPROJECT_ADD(box2d
  SOURCE_DIR ${CRAP_LIBRARIES_PATH}/Box2D
  PREFIX ${CMAKE_BINARY_DIR}/Box2D/Build
  CMAKE_ARGS ${Box2D_args}
  BINARY_DIR ${CRAP_LIBRARIES_PATH}/Box2D/Build
  INSTALL_COMMAND ""
)
