SET(CRAP_RUNTIME_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/runtime/include)
IF(LINUX)
  SET(CRAP_RUNTIME_LIBRARY crap_runtime)
ENDIF(LINUX)

INCLUDE_DIRECTORIES(${CRAP_RUNTIME_INCLUDE_DIR})
LINK_DIRECTORIES(${CMAKE_BIN_DIR}/runtime/)
