SET(CRAP_ENGINE_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/engine/include)
IF(LINUX)
  SET(CRAP_ENGINE_LIBRARY crap_engine)
ENDIF(LINUX)

INCLUDE_DIRECTORIES(${CRAP_ENGINE_INCLUDE_DIR})
LINK_DIRECTORIES(${CMAKE_BIN_DIR}/engine/)
