SET(CRAP_VIDEO_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/video/include)
IF(LINUX)
  SET(CRAP_VIDEO_LIBRARY crap_video)
ENDIF(LINUX)

INCLUDE_DIRECTORIES(${CRAP_VIDEO_INCLUDE_DIR})
LINK_DIRECTORIES(${CMAKE_BIN_DIR}/video/)
