SET(CRAP_INTERFACES_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/interfaces/include)
IF(LINUX)
  SET(CRAP_INTERFACES_LIBRARY crap_interfaces)
ENDIF(LINUX)

INCLUDE_DIRECTORIES(${CRAP_INTERFACES_INCLUDE_DIR})
LINK_DIRECTORIES(${CMAKE_BIN_DIR}/interfaces/)
