INCLUDE(ExternalProject)

SET(GLFW_ARGS -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF-DGLFW_INSTALL=OFF)

IF(WIN32)
SET(GLFW_ARGS ${GLFW_ARGS})
ELSE()
SET(GLFW_ARGS ${GLFW_ARGS})
ENDIF()

EXTERNALPROJECT_ADD(glfw_lib
  PREFIX ${CMAKE_BINARY_DIR}/glfw
  SOURCE_DIR ${CRAP_LIBRARIES_PATH}/glfw
  CMAKE_ARGS ${GLFW_ARGS}
  BINARY_DIR ${CMAKE_BINARY_DIR}/glfw
  INSTALL_COMMAND ""
)

INCLUDE_DIRECTORIES(${CRAP_LIBRARY_PATH}/glfw/include)
IF(WIN32)
    SET(GLFW_LIBRARY ${CMAKE_BINARY_DIR}/glfw/src/$<CONFIGURATION>/glfw3.lib)
ELSE()
    SET(GLFW_LIBRARY ${CMAKE_BINARY_DIR}/glfw/src/libglfw3.a)
ENDIF()
